name: Deploy to GitHub Pages

on:
  push:
    branches: [convite-next] # ou master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Node.js ğŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: '18' # ou a versÃ£o que vocÃª estÃ¡ usando
          
      - name: Install dependencies ğŸ“¦
        run: npm ci # ou yarn install --frozen-lockfile
        
      - name: Build ğŸ—ï¸
        run: npm run build # isso deve gerar o diretÃ³rio 'out'
        
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: convite-next
          folder: out
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          single-commit: true